# Stage 1: Build React app
FROM node:22.17.0-alpine AS builder
WORKDIR /app
COPY flow-ui/package*.json ./
RUN npm install --frozen-lockfile
COPY flow-ui/ .
COPY flow-ui/.env ./
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY flow-ui/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]